[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
arc-swap = "1.6.0"
axum-extra = { version = "0.7.0", features = ["cookie"] }
figment = { version = "0.10.8", features = ["json", "env", "yaml"] }
lazy_static = "1.4.0"
once_cell = "1.17.1"
serde = { version = "1.0.154", features = ["derive"] }
slog = { version = "2.7.0", features = ["nested-values", "max_level_trace"] }
thiserror = "1.0.39"
tracing = "0.1.37"


[lib]
path = "src/lib.rs"
