[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.6.0"
axum-extra = { version = "0.7.0", features = ["cookie"] }
diesel = { version = "2.0.3", features = ["r2d2", "postgres", "chrono", "time", "uuid", "serde_json", "extras"] }
diesel_migrations = { version = "2.0.0", features = ["postgres"] }
lazy_static = "1.4.0"
once_cell = "1.17.1"
slog = { version = "2.7.0", features = ["nested-values", "max_level_trace"] }
thiserror = "1.0.39"
tracing = "0.1.37"


[lib]
path = "src/lib.rs"
