# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-toml
          - id: check-yaml
          - id: pretty-format-json
            args: ["--indent=4", "--autofix"]
          - id: check-added-large-files
            args: ['--maxkb=2048']

    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: cargo-check

    - repo: local
      hooks:
        - id: clippy
          name: cargo clippy
          description: Run the Clippy linter on the package.
          entry: cargo clippy
          args: [ "--all-features", "--tests", "--" ]
          language: system
          types: [ rust ]
          pass_filenames: false
        - id: fmt
          name: cargo fmt (nightly)
          description: Format files with cargo fmt.
          entry: cargo +nightly fmt
          language: system
          types: [rust]
          args: ["--"]
