[workspace]
members = [
	"backend",
	"crates/common",
	"crates/infrastructure",
	"crates/logger"
]

[workspace.dependencies]
axum = "0.6.10"
tower-http = { version = "0.4.0", features = ["cors", "fs", "compression-gzip"] }


[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false
repository = "https://github.com/widnyana/env-compare"
authors = ["Widnyana Putra <wid@widnyana.web.id>"]


[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "z"
panic = 'abort'
strip = "true"
