# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "common/src/schema/db/schema.rs"

# skip generating missing sql type definitions
generate_missing_sql_type_definitions = true
