newline_style = "Unix"

# comments
format_code_in_doc_comments = true
max_width = 120
normalize_comments = true
wrap_comments = false

# imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
