edition = "2021"
newline_style = "Unix"
#struct_lit_single_line = false
#overflow_delimited_expr = true
chain_width = 60
#format_code_in_doc_comments = true
max_width = 120
#normalize_comments = true
#wrap_comments = true
#imports_layout = "HorizontalVertical"
#group_imports = "StdExternalCrate"
#imports_granularity = "Crate"
#merge_imports = true
merge_derives = true
