newline_style = "Unix"

# comments
format_code_in_doc_comments = true
max_width = 180
normalize_comments = true
wrap_comments = true

# imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
