[package]
name = "backend"
version = "0.1.0"
edition = "2021"
publish = false
authors = [
    "Widnyana Putra <wid@widnyana.web.id>"
]


[dependencies]
axum = { workspace = true, features = ["headers"] }
dotenvy = "0.15.6"
hyper = "0.14.24"
tokio = { version = "1.26.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["cors", "fs", "compression-gzip", "metrics", "tower", "trace", "add-extension", "auth", "base64", "full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

