# Default settings
run_mode: "development"
port: 3000

database:
  name: "caster_rust"
  url: "postgresql://env-compare:password@localhost:5432/env-compare"
  debug: true
  pool:
    min: 5
    max: 100

log:
  level: "INFO"
  format: "json"

redis:
  url: "localhost:6379"
