# Default settings
run_mode: "development"
port: 3000

database:
  name: "env-compare"
  dsn: "postgresql://env-compare:password@localhost:5432/env-compare"
  debug: true
  pool:
    min: 5
    max: 100
    idle_timeout: 60    # in seconds
    connect_timeout: 5  # in seconds

log:
  level: "INFO"
  format: "json"

redis:
  url: "localhost:6379"

tracing:
  otel_address: "http://localhost:4137"
  otel_sample_ratio: 1.0
  db_tracing: true
